module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "amber-400": "var(--amber-400)",
        black: "var(--black)",
        "blue-100": "var(--blue-100)",
        "blue-400": "var(--blue-400)",
        "blue-600": "var(--blue-600)",
        "blue-800": "var(--blue-800)",
        "blue-gray100": "var(--blue-gray100)",
        "blue-gray200": "var(--blue-gray200)",
        "blue-gray300": "var(--blue-gray300)",
        "blue-gray400": "var(--blue-gray400)",
        "blue-gray600": "var(--blue-gray600)",
        "blue-gray900": "var(--blue-gray900)",
        defaultalert: "var(--defaultalert)",
        defaultwhite: "var(--defaultwhite)",
        "green-100": "var(--green-100)",
        "green-500": "var(--green-500)",
        "green-800": "var(--green-800)",
        "indigo-600": "var(--indigo-600)",
        "overlaydark-50": "var(--overlaydark-50)",
        "overlaydark-75": "var(--overlaydark-75)",
        "purple-100": "var(--purple-100)",
        "purple-400": "var(--purple-400)",
        "purple-700": "var(--purple-700)",
        "purple-800": "var(--purple-800)",
        "red-100": "var(--red-100)",
        "red-400": "var(--red-400)",
        "red-800": "var(--red-800)",
        "rose-600": "var(--rose-600)",
        "rose-700": "var(--rose-700)",
        "rose-900": "var(--rose-900)",
        "violet-300": "var(--violet-300)",
        "warm-gray800": "var(--warm-gray800)",
        white: "var(--white)",
        "yellow-100": "var(--yellow-100)",
        "yellow-500": "var(--yellow-500)",
        "yellow-800": "var(--yellow-800)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "body-l": "var(--body-l-font-family)",
        "body-m": "var(--body-m-font-family)",
        "body-s": "var(--body-s-font-family)",
        "body-XL": "var(--body-XL-font-family)",
        "body-XS": "var(--body-XS-font-family)",
        "body-XXL": "var(--body-XXL-font-family)",
        "button-l": "var(--button-l-font-family)",
        "button-m": "var(--button-m-font-family)",
        "button-XL": "var(--button-XL-font-family)",
        "caption-m": "var(--caption-m-font-family)",
        "heading-1-m": "var(--heading-1-m-font-family)",
        "heading-2": "var(--heading-2-font-family)",
        "heading-4": "var(--heading-4-font-family)",
        "heading-5": "var(--heading-5-font-family)",
        "heading-6": "var(--heading-6-font-family)",
        "subtitle-m": "var(--subtitle-m-font-family)",
        "subtitle-XL": "var(--subtitle-XL-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: {
        "shadow-dark-m": "var(--shadow-dark-m)",
        "shadow-dark-XL": "var(--shadow-dark-XL)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
